import ConditionalHeader from '@/components/layout/ConditionalHeader';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import FloatingCart from '@/components/cart/FloatingCart';
import NetworkStatus from '@/components/common/NetworkStatus';
import QueryProvider from '@/providers/QueryProvider';

export const metadata = {
   title: 'Food Delivery App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
   return (
      <html>
         <body className="min-h-full flex flex-col">
            <QueryProvider>
               <ConditionalHeader />
               {children}
               <FloatingCart />
               <Toaster />
               <NetworkStatus />
            </QueryProvider>
         </body>
      </html>
   );
}
